# Generated by Django 4.1.6 on 2023-08-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('L1_Engine', models.CharField(max_length=200)),
                ('Primary_Execution_Team', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'mytest',
            },
        ),
    ]
